version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Logging into AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image (with push)...
      - npm run push
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'public/**/*'
